name = "ebay-accounting-belgium"
main = "./workers/app.ts"
compatibility_date = "2026-07-09"
compatibility_flags = ["nodejs_compat"]

[cache]
enabled = true

[exports.default]
type = "worker"

[exports.default.cache]
enabled = false

[assets]
directory = "./build/client"

[dev]
ip = "0.0.0.0"
port = 5173

[observability]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
head_sampling_rate = 1

[limits]
cpu_ms = 30000
